src/Padrinly/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Padrinly.Common.Extensions;
using Padrinly.Data;
using Padrinly.Domain.Enums;
using Padrinly.Models;
using System.Diagnostics;

namespace Padrinly.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        [Authorize(Roles = "Institution,Admin,Person,Student,Patron")]
        public async Task<IActionResult> Index()
        {
            var userId = User.GetUserId();

            ViewBag.UserId = userId;

            var user = await _context.Persons
                .FirstOrDefaultAsync(p => p.IdUser == userId);

            if(user != null) 
            {
                if (user.Type == TypePerson.Patron)
                {
                    var patronList = await _context.PersonPatrons
                        .Where(pp => pp.IdPatron == user.IdUser)
                        .ToListAsync();

                    var person = _context.Persons.FirstOrDefault(p => p.IdUser == userId);
                    ViewBag.IsPatron = true;
                    ViewBag.PersonId = person.Id;

                    var studentIds = patronList.Select(pp => pp.IdStudent).ToList();

                    var students = await _context.Persons
                        .Where(s => studentIds.Contains(s.IdUser.Value))
                        .ToListAsync();

                    ViewBag.PatronList = students;
                }
            }

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Padrinly/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Metadata;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Identity.Client;
using NuGet.Protocol;
using Padrinly.Common.Extensions;
using Padrinly.Data;
using Padrinly.Domain.Entities;
using Padrinly.Domain.Enums;
using Padrinly.Models;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace Padrinly.Controllers
{
    public class PersonController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private string _filePath;

        public PersonController(ApplicationDbContext context, UserManager<User> userManager, SignInManager<User> signInManager, IWebHostEnvironment env)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _filePath = env.WebRootPath;
        }

        // GET: Person
        [Authorize(Roles = "Institution")]
        public async Task<IActionResult> Index()
        {
            var students = _context.Persons.Include(p => p.User)
                                .Where(p => p.Type == TypePerson.Student);

            var responsibles = _context.Persons.Include(p => p.User)
                                .Where(p => p.Type == TypePerson.Responsabile);

            var combinedPersons = await students.Union(responsibles).ToListAsync();

            return View(combinedPersons);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> InstitutionIndex()
        {
            var allUsers = _context.Persons.Include(p => p.User)
                .Where(u => u.Type == TypePerson.Institution)
                .ToList();

            return View(allUsers);
        }

        [Authorize(Roles = "Student")]
        public async Task<IActionResult> PatronIndex(int id)
        {
            var patrons = await _context.PersonPatrons
                .Where(pp => pp.IdStudent == id)
                .ToListAsync();

            var patronList = new List<Person>();

            foreach(var patron in patrons)
            {
                var selectPatron = await _context.Persons.FirstOrDefaultAsync(p => p.IdUser == patron.IdPatron);
                patronList.Add(selectPatron);
            }

            ViewBag.PatronList = patronList;

            return View(patronList);
        }

        // GET: Person/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var listPost = await _context.Posts
                .Where(p => p.IdUser == id)
                .ToListAsync();

            ViewBag.ListPost = listPost;

            var person = await _context.Persons
                .Include(p => p.Institution)
                .Include(p => p.Responsible)
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.IdUser == id);

            var userId = User.GetUserId();

            if(User.IsInRole("Institution") || User.IsInRole("Patron") || User.IsInRole("Admin"))
            {
                return View(person);
            }

            if (person.IdUser != userId)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: Person/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["IdInstitution"] = new SelectList(_context.Persons, "Id", "Address");
            ViewData["IdResponsible"] = new SelectList(_context.Persons, "Id", "Address");
            ViewData["IdUser"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Person/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Name,Email,Password,PhoneNumber,BirthDate,IsAnonimous,AvatarFileName,AvatarInternalName,Type,FirstDocument,SecondDocument,Address,Neighborhood,City,State,PostalCode,Number,Complement,CreatedBy,UpdatedBy,CreatedAt,UpdatedAt")] Person person, IFormFile? avatarFile)
        {
            if (ModelState.IsValid)
            {
                // Cria usuário antes de criar Instituição
                var user = new User
                {
                    UserName = person.Email,
                    NormalizedUserName = person.Email.ToUpper(),
                    Email = person.Email,
                    NormalizedEmail = person.Email.ToUpper(),
                    PhoneNumber = person.PhoneNumber
                };

                var result = await _userManager.CreateAsync(user, person.Password);
                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(user, person.Type.ToString().ToUpper());
                }

                if (avatarFile != null)
                {
                    var name = SaveFile(avatarFile);
                    person.AvatarFileName = name;
                }
                person.IdUser = user.Id;
                person.Type = TypePerson.Institution;

                _context.Add(person);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(InstitutionIndex));
            }
            ViewData["IdInstitution"] = new SelectList(_context.Persons, "Id", "Address", person.IdInstitution);
            ViewData["IdResponsible"] = new SelectList(_context.Persons, "Id", "Address", person.IdResponsible);
            ViewData["IdUser"] = new SelectList(_context.Users, "Id", "Id", person.IdUser);
            return View(person);
        }

        [HttpGet]
        [Authorize(Roles = "Institution")]
        public async Task<IActionResult> CreateStudent()
        {
            var persons = await _context.Persons
                .Where(p => p.Type == TypePerson.Responsabile)
                .ToListAsync();

            ViewBag.ResponsibleList = persons
                .Select(p => new SelectListItem
                {
                    Value = p.Id.ToString(),
                    Text = p.Name
                })
                .ToList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Institution")]
        public async Task<IActionResult> CreateStudent(StudentResponsibleViewModel model, IFormFile? avatarFileName)
        {
            if (!ModelState.IsValid && model.IsNewResponsible)
            {
                return View(model);
            }

            if (model.IsNewResponsible)
            {
                await CreateNewResponsible(model);
            }
            else
            {
                var selectedResponsible = await _context.Persons.FindAsync(model.SelectedPersonId);
                ViewSelectedResponsible(model, selectedResponsible);
            }

            var studentUser = new User
            {
                UserName = model.StudentEmail,
                NormalizedUserName = model.StudentEmail.ToUpper(),
                Email = model.StudentEmail,
                NormalizedEmail = model.StudentEmail.ToUpper(),
                PhoneNumber = model.ResponsiblePhoneNumber,
            };

            await _userManager.CreateAsync(studentUser, model.Password);

            if (avatarFileName != null)
            {
                var name = SaveFile(avatarFileName);
                model.AvatarFileName = name;
            }


            int userIdLoged = User.GetUserId();
            var personIDLoged = await _context.Persons.FirstOrDefaultAsync(pi => pi.IdUser == userIdLoged);

            var student = new Person
            {
                Name = model.StudentName,
                BirthDate = model.StudentBirthDate,
                IdResponsible = model.IdResponsible,
                Email = model.StudentEmail,
                PhoneNumber = model.ResponsiblePhoneNumber,
                Address = model.Address,
                Neighborhood = model.Neighborhood,
                City = model.City,
                State = model.State,
                PostalCode = model.PostalCode,
                Number = model.Number,
                Complement = model.Complement,
                Type = TypePerson.Student,
                FirstDocument = model.StudentFirstDocument,
                SecondDocument = model.StudentSecondtDocument,
                IdUser = studentUser.Id,
                Password = model.Password,
                IdInstitution = personIDLoged.Id,
                AvatarFileName = model.AvatarFileName
            };

            await _userManager.AddToRoleAsync(studentUser, student.Type.ToString().ToUpper());

            _context.Add(student);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private async Task CreateNewResponsible(StudentResponsibleViewModel model)
        {
            var responsible = new Person
            {
                Name = model.ResponsibleName,
                BirthDate = model.ResponsibleBirthDate,
                Email = model.ResponsibleEmail,
                PhoneNumber = model.ResponsiblePhoneNumber,
                Address = model.Address,
                Neighborhood = model.Neighborhood,
                City = model.City,
                State = model.State,

src/Padrinly/Controllers/PersonPatronController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Padrinly.Common.Extensions;
using Padrinly.Data;
using Padrinly.Domain.Entities;
using Padrinly.Domain.Enums;

namespace Padrinly.Controllers
{
    public class PersonPatronController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public PersonPatronController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Affiliate()
        {
            var students = await _context.Persons
                .Where(s => s.Type == TypePerson.Student)
                .ToListAsync();

            var rnd = new Random();
            var randomStudent = students[rnd.Next(students.Count)];

            var userId = User.GetUserId();

            var patron = await _context.Persons
                .FirstOrDefaultAsync(p => p.IdUser == userId);

            var patronList = await _context.PersonPatrons
                .Where(pp => pp.IdPatron == patron.IdUser)
                .ToListAsync();

            while (patronList.Any(pp => pp.IdStudent == randomStudent.Id))
            {
                randomStudent = students[rnd.Next(students.Count)];
            }
            var personPatron = new PersonPatron
            {
                IdPatron = patron.IdUser.Value,
                IdStudent = randomStudent.IdUser.Value,
            };

            _context.Add(personPatron);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Home");
        }
    }
}

src/Padrinly/Views/Home/Index.cshtml
@using Padrinly.Common.Extensions
@model Padrinly.Domain.Entities.Person
@{
    ViewData["Title"] = "Página inicial";
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Fonte Montserrat Alternates-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <!-- Fonte Montserrat -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">


</head>

@if (User.IsInRole("Patron") && ViewBag.IsPatron != true)
{
    <body class="ImagemBoasVindas">
    <div>
      
        <div>
            <h1 class="BoasVindasT">Olá! Damos a você boas-vindas ao Padrin.Ly!</h1>
            <p class="BoasVindas">
                <br />
                <br />
                Hoje, milhões de crianças e adolescentes no Brasil enfrentam desafios diários devido à falta de acesso a recursos básicos como educação, saúde e alimentação. 
                A desigualdade social impede que muitos desses jovens alcancem seu pleno potencial, perpetuando um ciclo de pobreza e marginalização.
                <br />
                <br />
                Ao participar do nosso projeto, você estará fazendo mais do que apenas uma doação: 
                estará investindo no futuro de uma criança, oferecendo-lhe esperança, oportunidades e a chance de alcançar seus sonhos! 
                Além disso, estará contribuindo para a construção de uma sociedade mais justa, solidária e igualitária!  
                <br />
                <br />
                Para se tornar um padrinho ou madrinha, basta se cadastrar em nossa plataforma e automaticamente lhe atribuiremos uma criança. 
                Você receberá atualizações regulares sobre seu progresso e desenvolvimento, além de poder interagir com ela e sua família através de nossa plataforma!
            </p>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-sm">
                </div>
                <div class="col-sm" id="BoasVindasB">
                    <a asp-controller="Person" asp-action="CreatePatron" class="LargeButton">finalize seu registro agora!</a>
                </div>
                <div class="col-sm">
                </div>
            </div>
        </div>
    </div>
    
    </body >
}
else if (User.IsInRole("Patron") && ViewBag.IsPatron == true)

 {
    <!--Titulo da página + botões-->

    <div class="container">
        <div class="row">
            <div class="col">
            </div>
            <div class="col" id="TituloPagina">
                Bem vindo(a)!
            </div>
            <div class="col">
                <a asp-controller="Person" asp-action="Edit" asp-route-id="@ViewBag.PersonId" class="btnsettingssmall">Editar Perfil</a>
                <a asp-controller="Person" asp-action="Delete" asp-route-id="@ViewBag.PersonId" class="btnsettingsdel">Excluir conta</a>
            </div>
        </div>
    </div>
            
    <hr />

    <div class="container">
        <div class="row">
            <div class="col-sm-10">
            </div>
            <div class="col-sm">
                <a asp-controller="PersonPatron" asp-action="Affiliate" class="btnsettingssmall">nova afiliação</a>
            </div>
        </div>
    </div>

    <div class="BoxAfilhadoHome">
        <p id="TituloPagina">Meus afilhados</p>
            <hr />
            @foreach (var student in @ViewBag.PatronList)
            {
            <div class="container BoxAfilhadoHome">
                    <div class="row">
                        <div class="col-sm" style="margin: 10px">
                            <a asp-controller="Person" asp-action="Details" asp-route-id="@student.IdUser">
                                <img src="/images/@{@student.AvatarFileName}" width="500" /> 
                            </a>
                        </div>
                        <div class="col-sm BoxApresentacao">
                                <br />
                                <br />
                                <br />
                                Olá! É muito bom te conhecer! 
                                <br />
                                <br />
                                Meu nome é @student.Name!
                                <br />
                                <br />
                                Moro em @student.City!
                                <br />
                                <br />
                                Clique em minha foto para você conhecer mais sobre mim!
                        </div>
                    </div>
                </div>
            }
    </div>

 

 }


 else if (User.IsInRole("Institution"))

 {
    <!--Titulo da página-->

    <div class="container">
        <div class="row">
            <div class="col">
            </div>
            <div class="col" id="TituloPagina">
                Bem vindo(a)!
            </div>
            <div class="col">
            </div>
        </div>
    </div>

    <hr />

    <div class="container">
        <div class="row">
            <div class="col-sm DescribeOptions">
                Este é o espaço para os afilhados e responsáveis da sua instituição
                <br />
                <br />
                Espaço para cadastrar, editar e excluir dados de afilhados e responsáveis
            </div>
            <div class="col-sm" id="BoasVindasB">
                <a asp-controller="Person" asp-action="Index"><button class="XGButton">registro de afilhados/responsáveis</button></a>
            </div>
        </div>
    </div>
    <hr />

    <div class="col" id="BoasVindasB">
       
    </div>

   }


 else if(User.IsInRole("Student"))
 {
    <!--Titulo da página + botão sair-->

    <div class="container">
        <div class="row">
            <div class="col">
            </div>
            <div class="col" id="TituloPagina">
                Bem vindo(a)!
            </div>
            <div class="col">
            </div>
        </div>
    </div>

    <hr />


    <div class="container">
        <div class="row">
            <div class="col-sm DescribeOptions">
                Veja seu perfil e crie posts para seu padrinho!
                <br/>
                <br/>
                Use e abuse da criatividade! Escreva suas conquistas, o que gosta ou algo que te deixa feliz!
            </div>
            <div class="col-sm" id="BoasVindasB">
                <a asp-controller="Person" asp-action="Details" asp-route-id="@ViewBag.UserId"><button class="XGButton">Meu Perfil</button></a>
            </div>
        </div>
    </div>
    <hr />
   }


else if (User.IsInRole("Admin"))
{
    <!--Titulo da página + botão sair-->

    <div class="container">
        <div class="row">
            <div class="col">
            </div>
            <div class="col" id="TituloPagina">
                bem-vindo(a)!
            </div>
            <div class="col">
            </div>
        </div>
    </div>

    <hr />


    <div class="container">
        <div class="row">
            <div class="col-sm DescribeOptions">
                Espaço destinado para cadastro das instituições no programa
            </div>
            <div class="col-sm" id="BoasVindasB">
                <a asp-controller="Person" asp-action="InstitutionIndex" asp-route-id="@ViewBag.UserId"><button class="XGButton">ver instituições cadastradas</button></a>
            </div>
        </div>
    </div>
    <hr />
}